import 'package:f1_analyzer/model/lap_detail_model.dart';

final List<TyreModel> dummyLapDetails = [
  // Lap 1 - Fresh soft tires, cool track
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 1,
    trackTemperature: 20,
    frontLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 35,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 35,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 30,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 30,
    ),
  ),

  // Lap 2 - Early graining on soft compound
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 2,
    trackTemperature: 22,
    frontLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: true,
      tyrePressure: 23,
      tyreTemperature: 38,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: true,
      tyrePressure: 23,
      tyreTemperature: 38,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 21,
      tyreTemperature: 32,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 21,
      tyreTemperature: 32,
    ),
  ),

  // Lap 3 - Graining continues
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 3,
    trackTemperature: 24,
    frontLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: true,
      tyrePressure: 24,
      tyreTemperature: 42,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: true,
      tyrePressure: 24,
      tyreTemperature: 42,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 35,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 35,
    ),
  ),

  // Lap 4 - Front tires showing inner wear
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 4,
    trackTemperature: 26,
    frontLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 25,
      tyreTemperature: 45,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 25,
      tyreTemperature: 45,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 23,
      tyreTemperature: 38,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 23,
      tyreTemperature: 38,
    ),
  ),

  // Lap 5 - Tire color starting to change
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 5,
    trackTemperature: 28,
    frontLeft: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 26,
      tyreTemperature: 48,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 26,
      tyreTemperature: 48,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 24,
      tyreTemperature: 41,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 24,
      tyreTemperature: 41,
    ),
  ),

  // Lap 6 - More wear progression
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 6,
    trackTemperature: 30,
    frontLeft: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 27,
      tyreTemperature: 52,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 27,
      tyreTemperature: 52,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.outer,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 25,
      tyreTemperature: 44,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.outer,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 25,
      tyreTemperature: 44,
    ),
  ),

  // Lap 7 - Significant wear
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 7,
    trackTemperature: 32,
    frontLeft: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 28,
      tyreTemperature: 55,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 28,
      tyreTemperature: 55,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.outer,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 26,
      tyreTemperature: 47,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.outer,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 26,
      tyreTemperature: 47,
    ),
  ),

  // Lap 8 - End of first stint, heavy wear
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 8,
    trackTemperature: 34,
    frontLeft: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.center,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 29,
      tyreTemperature: 58,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.center,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 29,
      tyreTemperature: 58,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.outer,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 27,
      tyreTemperature: 50,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.outer,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 27,
      tyreTemperature: 50,
    ),
  ),

  // Lap 9 - PIT STOP - Fresh medium compound tires
  TyreModel(
    compound: TyreCompound.medium,
    lapNumber: 9,
    trackTemperature: 36,
    frontLeft: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 51,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 51,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 46,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 46,
    ),
  ),

  // Lap 10 - Medium tires settling in
  TyreModel(
    compound: TyreCompound.medium,
    lapNumber: 10,
    trackTemperature: 38,
    frontLeft: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 23,
      tyreTemperature: 54,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 23,
      tyreTemperature: 54,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 21,
      tyreTemperature: 49,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 21,
      tyreTemperature: 49,
    ),
  ),

  // Lap 11 - Medium tires showing wear
  TyreModel(
    compound: TyreCompound.medium,
    lapNumber: 11,
    trackTemperature: 40,
    frontLeft: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 24,
      tyreTemperature: 57,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.inner,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 24,
      tyreTemperature: 57,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 52,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.purpleTin,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 22,
      tyreTemperature: 52,
    ),
  ),

  // Lap 12 - End of race, medium tires heavily worn
  TyreModel(
    compound: TyreCompound.medium,
    lapNumber: 12,
    trackTemperature: 42,
    frontLeft: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.uneven,
      sidewallDefomation: true,
      isGraining: true,
      tyrePressure: 25,
      tyreTemperature: 60,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.uneven,
      sidewallDefomation: true,
      isGraining: true,
      tyrePressure: 25,
      tyreTemperature: 60,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.center,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 23,
      tyreTemperature: 55,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.greyBlack,
      wearPattern: WearPattern.center,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 23,
      tyreTemperature: 55,
    ),
  ),
];
