import 'package:f1_analyzer/lap_detail_model.dart';

final List<TyreModel> dummyLapDetails = [
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 1,
    frontLeft: LapTyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
    frontRight: LapTyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
    rearLeft: LapTyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
    rearRight: LapTyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
  ),
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 2,
    frontLeft: LapTyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
    frontRight: LapTyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
    rearLeft: LapTyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
    rearRight: LapTyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
      trackTemperature: 20,
    ),
  ),
];
