import 'package:f1_analyzer/model/lap_detail_model.dart';

final List<TyreModel> dummyLapDetails = [
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 1,
    trackTemperature: 20,
    frontLeft: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.matteBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
  ),
  TyreModel(
    compound: TyreCompound.soft,
    lapNumber: 2,
    trackTemperature: 24,
    frontLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
    frontRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
    rearLeft: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
    rearRight: TyreDetailModel(
      color: TyreColor.glossyBlack,
      wearPattern: WearPattern.even,
      sidewallDefomation: false,
      isGraining: false,
      tyrePressure: 20,
      tyreTemperature: 20,
    ),
  ),
];
